name: docker-publish
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # OBLIGATORIO en minúsculas para GHCR:
  OWNER_LC: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Normaliza a minúsculas por si el owner tiene mayúsculas
      - name: Normalize owner to lowercase
        id: lc
        run: |
          echo "val=$(echo '${{ env.OWNER_LC }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build & push WEB (What to do Cartagena)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.lc.outputs.val }}/whattodocartagena:latest